#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x ~/.config/wminit > /dev/null || ~/.config/wminit &
dex --autostart --environment bspwm &
kill latte-dock
sleep 1
latte-dock &

bspc monitor -d Term 🌎Web 💻Code 💬Chat 🎞Media 📚Book 🖌Graphics VIII IX X

bspc config border_width                  1
bspc config window_gap                    8
bspc config top_padding                   26
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a00"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#fe41ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

bspc config external_rules_command "~/.config/bspwm/winrules"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a systemsettings5 desktop='^7' state=floating follow=on
bspc rule -a kitty desktop='^1' follow=on
bspc rule -a okular desktop='^6' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv desktop='^5'
bspc rule -a Emacs desktop='^3' state=fullscreen follow=on
bspc rule -a emacs desktop='^3' state=fullscreen follow=on
bspc rule -a vlc desktop='^5'
bspc rule -a TelegramDesktop desktop='^4' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a notifications manage=off
bspc rule -a tooltip manage=off
