#!/bin/sh
#
# bspwm: external_rules_command
id=${1?};
class=$2;
instance=$3;
title=$(xtitle)
printf "id %s\nclass %s\ninst %s\ntitle %s\n\n" "$id" "$class" "$instance" "$title" >> /tmp/extout.txt
case $class in
    (drop) echo state=floating \ desktop=focused:focused;;
    ([fF]irefox) echo  desktop=^2;;
    ([dD]iscord) echo desktop=^4;;
    ([zZ]athura) echo state=tiled;;
    (Spotify) echo desktop=^5;;
    ([sS]urf) echo state=tiled;;
    ([eE]macs) echo desktop=^3;;
    ('')
        case $(ps -p "$(xdo pid "$id")" -o comm= 2>/dev/null) in
            (spotify) echo desktop=^5;;
        esac;;
esac;
case $instance in
    ("league of legends.exe") echo desktop=^2:^2 \ state=fullscreen;;
esac
case $title in
    ('Friends List') echo state=floating \ desktop=^2:^8;;
esac;
case $title in
    ('Microsoft Edge(dev)') echo desktop=^2;;
esac;
# vim: set ft=sh :sac
