alias nv='nvim'
alias ls='exa --icons'
alias l='ls -l'
alias ll='l -a'
alias la='ls -a'
alias lt='l --tree'
alias lta='lt -a'
alias p='paru'
fish_vi_key_bindings
set -ga PATH '/home/scott/.emacs.d/bin'
set -ga PATH '/home/scott/.local/bin'
